server:
  port: 8088

spring:
  thymeleaf:
    prefix: classpath:/static/html/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.111/rhyme?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wxs.blog.entity